"""add game_distribution

Revision ID: b9cb21031ca2
Revises: 006_daily_category
Create Date: 2026-04-17 21:06:51.397140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cb21031ca2'
down_revision: Union[str, None] = '006_daily_category'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_distributions',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('attempt_1', sa.Integer(), nullable=False),
    sa.Column('attempt_2', sa.Integer(), nullable=False),
    sa.Column('attempt_3', sa.Integer(), nullable=False),
    sa.Column('attempt_4', sa.Integer(), nullable=False),
    sa.Column('attempt_5', sa.Integer(), nullable=False),
    sa.Column('attempt_6', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['daily_songs.internal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_distributions')
    # ### end Alembic commands ###
